"""GitHub Pages site generator for converted Markdown documents.

Generates a static site structure suitable for GitHub Pages:
  - index.html with document listing and navigation
  - Per-document HTML pages from cleaned Markdown
  - Optional sidebar/TOC from chunk structure
  - _config.yml for Jekyll or direct HTML deployment

Operates on the outputs directory tree.
"""

from __future__ import annotations

import argparse
import html
import json
import re
from dataclasses import dataclass
from pathlib import Path

from scripts.common import load_config, resolve_path, setup_logging
from scripts.multi_format import DEFAULT_CSS, md_to_html

# ── Site generation ──────────────────────────────────────────────────────────

SITE_CSS = (
    DEFAULT_CSS
    + """
nav { background: #f8f8f8; padding: 1rem; margin-bottom: 2rem;
      border-bottom: 1px solid #ddd; }
nav a { margin-right: 1rem; text-decoration: none; color: #0366d6; }
nav a:hover { text-decoration: underline; }
.breadcrumb { color: #666; font-size: 0.9em; margin-bottom: 1rem; }
.card { border: 1px solid #e1e4e8; border-radius: 6px; padding: 1rem;
        margin-bottom: 1rem; }
.card h3 { margin-top: 0; }
.card a { text-decoration: none; color: #0366d6; }
footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #eee;
         color: #666; font-size: 0.85em; }
"""
)


def _page_wrapper(title: str, body: str, *, nav_html: str = "", css: str = SITE_CSS) -> str:
    """Wrap body HTML in a full page with nav and footer."""
    escaped_title = html.escape(title)
    return (
        f'<!DOCTYPE html>\n<html lang="en">\n<head>\n'
        f'<meta charset="utf-8">\n<meta name="viewport" content="width=device-width, initial-scale=1">\n'
        f"<title>{escaped_title}</title>\n<style>{css}</style>\n</head>\n"
        f"<body>\n{nav_html}\n{body}\n"
        f"<footer>Generated by pdf-to-markdown-pipeline</footer>\n"
        f"</body>\n</html>\n"
    )


# ── Page builders ────────────────────────────────────────────────────────────


@dataclass
class PageEntry:
    """A single page in the site."""

    title: str
    relative_path: str
    source_md: str


def build_nav_html(pages: list[PageEntry], current: str = "") -> str:
    """Build a navigation bar HTML fragment."""
    links = ['<a href="index.html">Home</a>']
    for page in pages[:20]:
        cls = ' style="font-weight:bold"' if page.relative_path == current else ""
        links.append(f'<a href="{html.escape(page.relative_path)}"{cls}>{html.escape(page.title)}</a>')
    return f"<nav>{''.join(links)}</nav>"


def build_index_page(
    site_title: str,
    pages: list[PageEntry],
    *,
    description: str = "",
) -> str:
    """Build the index.html landing page."""
    cards: list[str] = []
    for page in pages:
        card = (
            f'<div class="card"><h3><a href="{html.escape(page.relative_path)}">'
            f"{html.escape(page.title)}</a></h3>"
            f"<p>{html.escape(page.source_md)}</p></div>"
        )
        cards.append(card)

    body_parts = [f"<h1>{html.escape(site_title)}</h1>"]
    if description:
        body_parts.append(f"<p>{html.escape(description)}</p>")
    body_parts.append("<h2>Documents</h2>")
    body_parts.extend(cards)

    nav = build_nav_html(pages)
    return _page_wrapper(site_title, "\n".join(body_parts), nav_html=nav)


def build_document_page(
    page: PageEntry,
    md_text: str,
    all_pages: list[PageEntry],
) -> str:
    """Build an individual document HTML page from Markdown."""
    # Use multi_format's md_to_html but extract the body
    full_html = md_to_html(md_text, title=page.title, css="")
    # Extract body content between <body> and </body>
    body_match = re.search(r"<body>(.*?)</body>", full_html, re.DOTALL)
    body = body_match.group(1) if body_match else full_html

    nav = build_nav_html(all_pages, current=page.relative_path)
    breadcrumb = f'<div class="breadcrumb"><a href="index.html">Home</a> &gt; {html.escape(page.title)}</div>'
    return _page_wrapper(page.title, breadcrumb + body, nav_html=nav)


# ── Site generation engine ───────────────────────────────────────────────────


def collect_pages(input_root: Path) -> list[PageEntry]:
    """Scan Markdown files and build page entries."""
    md_files = sorted(p for p in input_root.rglob("*.md") if p.is_file())
    pages: list[PageEntry] = []
    for md_path in md_files:
        relative = md_path.relative_to(input_root)
        html_path = str(relative.with_suffix(".html"))
        # Extract title from first heading
        text = md_path.read_text(encoding="utf-8")
        title = md_path.stem
        for line in text.split("\n")[:10]:
            if line.strip().startswith("# "):
                title = line.strip().lstrip("# ").strip()
                break
        pages.append(
            PageEntry(
                title=title,
                relative_path=html_path,
                source_md=str(relative),
            )
        )
    return pages


def generate_site(
    input_root: Path,
    output_dir: Path,
    *,
    site_title: str = "Documentation",
    description: str = "",
) -> list[Path]:
    """Generate a complete static site from Markdown files."""
    if not input_root.exists():
        raise FileNotFoundError(f"Input directory not found: {input_root}")

    pages = collect_pages(input_root)
    if not pages:
        raise FileNotFoundError(f"No markdown files found under: {input_root}")

    output_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    # Generate index
    index_html = build_index_page(site_title, pages, description=description)
    index_path = output_dir / "index.html"
    index_path.write_text(index_html, encoding="utf-8")
    written.append(index_path)

    # Generate per-document pages
    for page in pages:
        md_path = input_root / page.source_md
        md_text = md_path.read_text(encoding="utf-8")
        page_html = build_document_page(page, md_text, pages)
        out_path = output_dir / page.relative_path
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(page_html, encoding="utf-8")
        written.append(out_path)

    return written


def write_site_manifest(pages: list[PageEntry], output_path: Path) -> Path:
    """Write a JSON manifest of the generated site."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    data = {
        "pages": len(pages),
        "entries": [{"title": p.title, "path": p.relative_path, "source": p.source_md} for p in pages],
    }
    output_path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return output_path


# ── CLI ──────────────────────────────────────────────────────────────────────


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate a GitHub Pages static site from Markdown files.")
    parser.add_argument("--input", type=Path, help="Cleaned Markdown directory")
    parser.add_argument("--output-dir", type=Path, help="Output directory for the site")
    parser.add_argument("--title", default="Documentation", help="Site title")
    parser.add_argument("--description", default="", help="Site description")
    parser.add_argument("--config", type=Path, help="Path to pipeline.yaml")
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()

    cfg = load_config(args.config)
    log = setup_logging("ghpages", cfg)

    input_path = (args.input or resolve_path(cfg["paths"]["output_cleaned_md"])).resolve()
    output_dir = (args.output_dir or resolve_path("outputs/site")).resolve()

    try:
        written = generate_site(
            input_path,
            output_dir,
            site_title=args.title,
            description=args.description,
        )
        log.info("generated %d page(s) → %s", len(written), output_dir)

    except FileNotFoundError as exc:
        log.error("file not found: %s", exc)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
